# Generated by Django 5.1.1 on 2024-10-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chismis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chismis', models.CharField(max_length=255)),
                ('chismis_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
